
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Login_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Login_Frame
     */
    public Login_Frame() {
        initComponents();
    
        
        Close_button.setContentAreaFilled(false);  // Makes the button background transparent
        Close_button.setOpaque(false);             // Ensures the transparency is respected
        Close_button.setBorderPainted(false);
        
        Minimize_button.setContentAreaFilled(false);  // Makes the button background transparent
        Minimize_button.setOpaque(false);             // Ensures the transparency is respected
        Minimize_button.setBorderPainted(false);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UsernameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Sign_up = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Minimize_button = new javax.swing.JButton();
        Close_button = new javax.swing.JButton();
        ShowPass = new javax.swing.JCheckBox();
        PasswordText = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Panel.setBackground(new java.awt.Color(0, 102, 102));
        Login_Panel.setForeground(new java.awt.Color(204, 255, 204));
        Login_Panel.setName(""); // NOI18N
        Login_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        Login_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 240, 30));

        UsernameText.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        UsernameText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        UsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextActionPerformed(evt);
            }
        });
        Login_Panel.add(UsernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 230, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username or email");
        Login_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 240, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Icon.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Login_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Password_Icon.png"))); // NOI18N
        Login_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        Sign_up.setBackground(new java.awt.Color(0, 102, 102));
        Sign_up.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Sign_up.setForeground(new java.awt.Color(255, 255, 255));
        Sign_up.setText("Sign Up");
        Sign_up.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        Sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_upActionPerformed(evt);
            }
        });
        Login_Panel.add(Sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 110, 36));
        Login_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 105, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGIN_LOGO.png"))); // NOI18N
        Login_Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        Login.setBackground(new java.awt.Color(0, 102, 102));
        Login.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Login");
        Login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Login_Panel.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 110, 36));

        Minimize_button.setBackground(new java.awt.Color(0, 51, 51));
        Minimize_button.setForeground(new java.awt.Color(0, 102, 102));
        Minimize_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Minimize_Icon.png"))); // NOI18N
        Minimize_button.setBorder(null);
        Minimize_button.setBorderPainted(false);
        Minimize_button.setFocusPainted(false);
        Minimize_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minimize_buttonActionPerformed(evt);
            }
        });
        Login_Panel.add(Minimize_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 40, 40));

        Close_button.setBackground(new java.awt.Color(0, 51, 51));
        Close_button.setForeground(new java.awt.Color(0, 51, 51));
        Close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close_Icon.png"))); // NOI18N
        Close_button.setBorder(null);
        Close_button.setBorderPainted(false);
        Close_button.setFocusPainted(false);
        Close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_buttonActionPerformed(evt);
            }
        });
        Login_Panel.add(Close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 40, 40));

        ShowPass.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        ShowPass.setForeground(new java.awt.Color(255, 255, 255));
        ShowPass.setText("Show Password");
        ShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassActionPerformed(evt);
            }
        });
        Login_Panel.add(ShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 160, 20));

        PasswordText.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        PasswordText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });
        Login_Panel.add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 230, 30));

        getContentPane().add(Login_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 380, 640));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 520, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Frame.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextActionPerformed
       
    }//GEN-LAST:event_UsernameTextActionPerformed

    private void Sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_upActionPerformed
        
        Sign_Up_Frame Signup = new Sign_Up_Frame();
        Signup.show();
        
        dispose();
    }//GEN-LAST:event_Sign_upActionPerformed
    
    private int getUserIdByUsername(String username) {
        int userId = -1;
        String query = "SELECT user_id FROM users WHERE username = ?";
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gulong_rentals", "username", "password");
             PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, username);  // Set the username parameter
            
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    userId = rs.getInt("user_id");  // Get the user_id from the result set
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        return userId;
    }
    
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String username = UsernameText.getText();
    String password = new String(PasswordText.getPassword());
    String email = UsernameText.getText();

    // Validate input
    if (username.equals("") || password.equals("")) {
        JOptionPane.showMessageDialog(null, "Please fill out both username and password");
        return;  // Exit if username or password is empty
    }

    // Attempt to log the user in
    int userId = -1;  // Declare userId variable to store the logged-in user^'s ID

    // Debugging log
    System.out.println("Authenticating user...");

    if (authenticateUser(username, password)) {
        userId = getUserIdByUsername(username);  // Retrieve user_id based on the username
    } else if (authenticateUser(email, password)) {
        userId = getUserIdByEmail(email);
    }

    if (userId != -1) {
    JOptionPane.showMessageDialog(null, "Login successful!");

    // Create the main menu instance with userId passed to its constructor
    Main_Menu_Frame mainMenu = new Main_Menu_Frame(userId);

    // Proceed to the main menu
    dispose();  // Close the login window
    mainMenu.setVisible(true);  // Show the main menu
    mainMenu.A_N.setText(username);
} else {
    JOptionPane.showMessageDialog(null, "Invalid username or password.");
}
    }
    
    
    
    public static class DatabaseManager {

        public int getUserIdByUsername(String username) {
            int userId = -1;
            String query = "SELECT user_id FROM users WHERE username = ?";
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gulong_rentals", "username", "password");
                 PreparedStatement stmt = conn.prepareStatement(query)) {

                stmt.setString(1, username);  // Set the username parameter

                try (ResultSet rs = stmt.executeQuery()) {
                    if (rs.next()) {
                        userId = rs.getInt("user_id");  // Get the user_id from the result set
                    }
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
            return userId;
        }
    }

// Method to retrieve the user_id based on the email
    private int getUserIdByEmail(String email) {
    int userId = -1;
    String query = "SELECT user_id FROM users WHERE email = ?";  // Assuming 'users' table has 'user_id' and 'email'

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gulong_rentals", "username", "password");
         PreparedStatement stmt = conn.prepareStatement(query)) {

        stmt.setString(1, email);  // Set the email parameter

        try (ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                userId = rs.getInt("user_id");  // Retrieve the user_id
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return userId;
}

// Method to authenticate user by checking credentials in the database
    private boolean authenticateUser(String username, String password) {
        String url = "jdbc:mysql://localhost:3306/gulong_rentals";
        String dbUsername = "root"; 
        String dbPassword = "";


        String query = "SELECT * FROM users WHERE (username = ? OR email = ?) AND password = ?";

        try (Connection connection = DriverManager.getConnection(url, dbUsername, dbPassword);
           PreparedStatement stmt = connection.prepareStatement(query)) {


            stmt.setString(1, username);
            stmt.setString(2, username);
            stmt.setString(3, password);  

        
            ResultSet rs = stmt.executeQuery();

      
            return rs.next(); 

        }
        catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
        }

        return false;
        
         
    }//GEN-LAST:event_LoginActionPerformed

    private void Close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_buttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Close_buttonActionPerformed

    private void Minimize_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minimize_buttonActionPerformed
        this.setState(Login_Frame.ICONIFIED);
    }//GEN-LAST:event_Minimize_buttonActionPerformed

    private void ShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassActionPerformed
        if (ShowPass.isSelected()) {
            PasswordText.setEchoChar((char)0);  // Show password in plain text
        } else {
            PasswordText.setEchoChar('*');  // Hide password (default echo character)
        }
    }//GEN-LAST:event_ShowPassActionPerformed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close_button;
    private javax.swing.JButton Login;
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JButton Minimize_button;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JCheckBox ShowPass;
    private javax.swing.JButton Sign_up;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
