import javax.swing.*;
import java.awt.*;

public class Main_Menu_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu_Frame
     */
    public Main_Menu_Frame() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        jTabbedPane2.setEnabledAt(0, false);  // Disable the first tab
        jTabbedPane2.setEnabledAt(1, false);
        jTabbedPane2.setEnabledAt(2, false);  // Disable the first tab
        jTabbedPane2.setEnabledAt(3, false);
        jTabbedPane2.setEnabledAt(4, false);  // Disable the first tab
        jTabbedPane2.setEnabledAt(5, false);
        
        
        Account.setContentAreaFilled(false);  // Makes the button background transparent
        Account.setOpaque(false);             // Ensures the transparency is respected
        Account.setBorderPainted(false);
        
        HomePanel.setBackground(new Color(255, 255, 255,0));
        VehiclePanel.setBackground(new Color(255, 255, 255,100));
        FeedbackPanel.setBackground(new Color(255, 255, 255,100));
        BookmarkPanel.setBackground(new Color(255, 255, 255,100));
        PaymentPanel.setBackground(new Color(255, 255, 255,100));
        NotificationPanel.setBackground(new Color(255, 255, 255,100));
        
        
        Home_Button.setOpaque(false);                // Ensures the button background is visible
        Home_Button.setBackground(Color.GRAY);      // Sets the background color to gray
        Home_Button.setBorderPainted(false);        // Removes the button's border
        Home_Button.setContentAreaFilled(true);
        
        Vehicle_Button.setOpaque(false);                // Ensures the button background is visible
        Vehicle_Button.setBackground(Color.GRAY);      // Sets the background color to gray
        Vehicle_Button.setBorderPainted(false);        // Removes the button's border
        Vehicle_Button.setContentAreaFilled(true);
        
        Feedback_Button.setOpaque(false);                // Ensures the button background is visible
        Feedback_Button.setBackground(Color.GRAY);      // Sets the background color to gray
        Feedback_Button.setBorderPainted(false);        // Removes the button's border
        Feedback_Button.setContentAreaFilled(true);
        
        Bookmark_Button.setOpaque(false);                // Ensures the button background is visible
        Bookmark_Button.setBackground(Color.GRAY);      // Sets the background color to gray
        Bookmark_Button.setBorderPainted(false);        // Removes the button's border
        Bookmark_Button.setContentAreaFilled(true);
        
        Payment_Button.setOpaque(false);                // Ensures the button background is visible
        Payment_Button.setBackground(Color.GRAY);      // Sets the background color to gray
        Payment_Button.setBorderPainted(false);        // Removes the button's border
        Payment_Button.setContentAreaFilled(true);
        
        Notification_Button.setOpaque(false);                // Ensures the button background is visible
        Notification_Button.setBackground(Color.GRAY);      // Sets the background color to gray
        Notification_Button.setBorderPainted(false);        // Removes the button's border
        Notification_Button.setContentAreaFilled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Account = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Vehicle_Button = new javax.swing.JButton();
        Feedback_Button = new javax.swing.JButton();
        Payment_Button = new javax.swing.JButton();
        Home_Button = new javax.swing.JButton();
        Bookmark_Button = new javax.swing.JButton();
        Notification_Button = new javax.swing.JButton();
        Notification_Button1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        VehiclePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        FeedbackPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BookmarkPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PaymentPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NotificationPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1920, 1280));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 105, 105));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Account_Icon.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, -1, 96));

        Account.setBackground(new java.awt.Color(0, 0, 0));
        Account.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        Account.setForeground(new java.awt.Color(255, 255, 255));
        Account.setText("ACCOUNT NAME");
        jPanel4.add(Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 40, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 100));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));

        Vehicle_Button.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        Vehicle_Button.setForeground(new java.awt.Color(255, 255, 255));
        Vehicle_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vehicle_Icon.png"))); // NOI18N
        Vehicle_Button.setToolTipText("Vehicle List");
        Vehicle_Button.setBorder(null);
        Vehicle_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vehicle_ButtonActionPerformed(evt);
            }
        });

        Feedback_Button.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        Feedback_Button.setForeground(new java.awt.Color(255, 255, 255));
        Feedback_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Feedback_Icon.png"))); // NOI18N
        Feedback_Button.setToolTipText("Feedbacks");
        Feedback_Button.setBorder(null);
        Feedback_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Feedback_ButtonActionPerformed(evt);
            }
        });

        Payment_Button.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        Payment_Button.setForeground(new java.awt.Color(255, 255, 255));
        Payment_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Payment_Icon.png"))); // NOI18N
        Payment_Button.setToolTipText("Payments");
        Payment_Button.setBorder(null);
        Payment_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Payment_ButtonActionPerformed(evt);
            }
        });

        Home_Button.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        Home_Button.setForeground(new java.awt.Color(255, 255, 255));
        Home_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home_Icon.png"))); // NOI18N
        Home_Button.setToolTipText("Home Page");
        Home_Button.setBorder(null);
        Home_Button.setFocusable(false);
        Home_Button.setIconTextGap(10);
        Home_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_ButtonActionPerformed(evt);
            }
        });

        Bookmark_Button.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        Bookmark_Button.setForeground(new java.awt.Color(255, 255, 255));
        Bookmark_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bookmark_Icon.png"))); // NOI18N
        Bookmark_Button.setToolTipText("Favorites");
        Bookmark_Button.setBorder(null);
        Bookmark_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bookmark_ButtonActionPerformed(evt);
            }
        });

        Notification_Button.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        Notification_Button.setForeground(new java.awt.Color(255, 255, 255));
        Notification_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Notification_Icon.png"))); // NOI18N
        Notification_Button.setToolTipText("Notification");
        Notification_Button.setBorder(null);
        Notification_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Notification_ButtonActionPerformed(evt);
            }
        });

        Notification_Button1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        Notification_Button1.setForeground(new java.awt.Color(255, 255, 255));
        Notification_Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit_Icon.png"))); // NOI18N
        Notification_Button1.setToolTipText("Notification");
        Notification_Button1.setBorder(null);
        Notification_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Notification_Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(Vehicle_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Feedback_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bookmark_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Payment_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Notification_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Notification_Button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Vehicle_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Feedback_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bookmark_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Payment_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Notification_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 554, Short.MAX_VALUE)
                .addComponent(Notification_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 1280));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel3.setText("HOME PAGE");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel3)
                .addContainerGap(968, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel3)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", HomePanel);

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel8.setText("VEHICLE PAGE");

        javax.swing.GroupLayout VehiclePanelLayout = new javax.swing.GroupLayout(VehiclePanel);
        VehiclePanel.setLayout(VehiclePanelLayout);
        VehiclePanelLayout.setHorizontalGroup(
            VehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclePanelLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(885, Short.MAX_VALUE))
        );
        VehiclePanelLayout.setVerticalGroup(
            VehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclePanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel8)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab2", VehiclePanel);

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel5.setText("FEEDBACK PAGE");

        javax.swing.GroupLayout FeedbackPanelLayout = new javax.swing.GroupLayout(FeedbackPanel);
        FeedbackPanel.setLayout(FeedbackPanelLayout);
        FeedbackPanelLayout.setHorizontalGroup(
            FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel5)
                .addContainerGap(848, Short.MAX_VALUE))
        );
        FeedbackPanelLayout.setVerticalGroup(
            FeedbackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel5)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab3", FeedbackPanel);

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel6.setText("BOOKMARK PAGE");

        javax.swing.GroupLayout BookmarkPanelLayout = new javax.swing.GroupLayout(BookmarkPanel);
        BookmarkPanel.setLayout(BookmarkPanelLayout);
        BookmarkPanelLayout.setHorizontalGroup(
            BookmarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookmarkPanelLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel6)
                .addContainerGap(825, Short.MAX_VALUE))
        );
        BookmarkPanelLayout.setVerticalGroup(
            BookmarkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookmarkPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel6)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab4", BookmarkPanel);

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel7.setText("PAYMENT PAGE");

        javax.swing.GroupLayout PaymentPanelLayout = new javax.swing.GroupLayout(PaymentPanel);
        PaymentPanel.setLayout(PaymentPanelLayout);
        PaymentPanelLayout.setHorizontalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentPanelLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel7)
                .addContainerGap(879, Short.MAX_VALUE))
        );
        PaymentPanelLayout.setVerticalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel7)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab5", PaymentPanel);

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel4.setText("NOTIFICATION PAGE");

        javax.swing.GroupLayout NotificationPanelLayout = new javax.swing.GroupLayout(NotificationPanel);
        NotificationPanel.setLayout(NotificationPanelLayout);
        NotificationPanelLayout.setHorizontalGroup(
            NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotificationPanelLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel4)
                .addContainerGap(734, Short.MAX_VALUE))
        );
        NotificationPanelLayout.setVerticalGroup(
            NotificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotificationPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel4)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab6", NotificationPanel);

        jPanel2.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 1760, 1060));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main_Menu_BG.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -190, 1920, 1270));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private void Vehicle_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vehicle_ButtonActionPerformed
        if (jTabbedPane2.getSelectedIndex() == 1) {
    // Tab is already selected, so hide it or disable it
            jTabbedPane2.setEnabledAt(1, false);  // Disable the tab so it won't be clickable
            jTabbedPane2.setSelectedIndex(-1);  // Deselect the tab (hide the content)
        }
        else {
    // Tab is not selected, so select it
            jTabbedPane2.setEnabledAt(1, true);  // Ensure the tab is enabled
            jTabbedPane2.setSelectedIndex(1);  // Select the tab
        }      
    }//GEN-LAST:event_Vehicle_ButtonActionPerformed

    private void Feedback_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Feedback_ButtonActionPerformed
        if (jTabbedPane2.getSelectedIndex() == 2) {
    // Tab is already selected, so hide it or disable it
            jTabbedPane2.setEnabledAt(2, false);  // Disable the tab so it won't be clickable
            jTabbedPane2.setSelectedIndex(-1);  // Deselect the tab (hide the content)
        }
        else {
    // Tab is not selected, so select it
            jTabbedPane2.setEnabledAt(2, true);  // Ensure the tab is enabled
            jTabbedPane2.setSelectedIndex(2);  // Select the tab
        } 
    }//GEN-LAST:event_Feedback_ButtonActionPerformed

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        
        if (jTabbedPane2.getSelectedIndex() == 0) {
    // Tab is already selected, so hide it or disable it
            jTabbedPane2.setEnabledAt(0, false);  // Disable the tab so it won't be clickable
            jTabbedPane2.setSelectedIndex(-1);  // Deselect the tab (hide the content)
        }
        else {
    // Tab is not selected, so select it
            jTabbedPane2.setEnabledAt(0, true);  // Ensure the tab is enabled
            jTabbedPane2.setSelectedIndex(0);  // Select the tab
        }
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void Payment_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Payment_ButtonActionPerformed
        if (jTabbedPane2.getSelectedIndex() == 4) {
    // Tab is already selected, so hide it or disable it
            jTabbedPane2.setEnabledAt(4, false);  // Disable the tab so it won't be clickable
            jTabbedPane2.setSelectedIndex(-1);  // Deselect the tab (hide the content)
        }
        else {
    // Tab is not selected, so select it
            jTabbedPane2.setEnabledAt(4, true);  // Ensure the tab is enabled
            jTabbedPane2.setSelectedIndex(4);  // Select the tab
        }
    }//GEN-LAST:event_Payment_ButtonActionPerformed

    private void Bookmark_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bookmark_ButtonActionPerformed
        if (jTabbedPane2.getSelectedIndex() == 3) {
    // Tab is already selected, so hide it or disable it
            jTabbedPane2.setEnabledAt(3, false);  // Disable the tab so it won't be clickable
            jTabbedPane2.setSelectedIndex(-1);  // Deselect the tab (hide the content)
        }
        else {
    // Tab is not selected, so select it
            jTabbedPane2.setEnabledAt(3, true);  // Ensure the tab is enabled
            jTabbedPane2.setSelectedIndex(3);  // Select the tab
        }
    }//GEN-LAST:event_Bookmark_ButtonActionPerformed

    private void Notification_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Notification_ButtonActionPerformed
        if (jTabbedPane2.getSelectedIndex() == 5) {
    // Tab is already selected, so hide it or disable it
            jTabbedPane2.setEnabledAt(5, false);  // Disable the tab so it won't be clickable
            jTabbedPane2.setSelectedIndex(-1);  // Deselect the tab (hide the content)
        }
        else {
    // Tab is not selected, so select it
            jTabbedPane2.setEnabledAt(5, true);  // Ensure the tab is enabled
            jTabbedPane2.setSelectedIndex(5);  // Select the tab
        }
    }//GEN-LAST:event_Notification_ButtonActionPerformed
        
    private void Notification_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Notification_Button1ActionPerformed
        
    }//GEN-LAST:event_Notification_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel BookmarkPanel;
    private javax.swing.JButton Bookmark_Button;
    private javax.swing.JPanel FeedbackPanel;
    private javax.swing.JButton Feedback_Button;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JButton Home_Button;
    private javax.swing.JPanel NotificationPanel;
    private javax.swing.JButton Notification_Button;
    private javax.swing.JButton Notification_Button1;
    private javax.swing.JPanel PaymentPanel;
    private javax.swing.JButton Payment_Button;
    private javax.swing.JPanel VehiclePanel;
    private javax.swing.JButton Vehicle_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
