import javax.swing.JOptionPane;


public class Sign_Up_Frame extends javax.swing.JFrame {

    
    public Sign_Up_Frame() {
        initComponents();
        
       
        Return_Login_Button.setContentAreaFilled(false);  // Makes the button background transparent
        Return_Login_Button.setOpaque(false);             // Ensures the transparency is respected
        Return_Login_Button.setBorderPainted(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Return_Login_Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Email_Address = new javax.swing.JTextField();
        Create_Account_Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Password2 = new javax.swing.JPasswordField();
        Password1 = new javax.swing.JPasswordField();
        ShowPass1 = new javax.swing.JCheckBox();
        ShowPass2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 520, 220));

        Return_Login_Button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Return_Login_Button.setForeground(new java.awt.Color(255, 255, 255));
        Return_Login_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back_Icon.png"))); // NOI18N
        Return_Login_Button.setText(" Return to Login page");
        Return_Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_Login_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Return_Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 240, 40));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sign_Up_Icon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        Username.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 260, 37));

        Email_Address.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Email_Address.setForeground(new java.awt.Color(0, 0, 0));
        Email_Address.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        Email_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_AddressActionPerformed(evt);
            }
        });
        jPanel1.add(Email_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 260, 37));

        Create_Account_Button.setBackground(new java.awt.Color(0, 102, 102));
        Create_Account_Button.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Create_Account_Button.setForeground(new java.awt.Color(255, 255, 255));
        Create_Account_Button.setText("Create Account");
        Create_Account_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        Create_Account_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_Account_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Create_Account_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 192, 35));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 120, 30));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 140, 30));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 120, 30));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 120, 30));

        Password2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Password2.setForeground(new java.awt.Color(0, 0, 0));
        Password2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        Password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password2ActionPerformed(evt);
            }
        });
        jPanel1.add(Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 260, 40));

        Password1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        Password1.setForeground(new java.awt.Color(0, 0, 0));
        Password1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        Password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password1ActionPerformed(evt);
            }
        });
        jPanel1.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 260, 40));

        ShowPass1.setForeground(new java.awt.Color(255, 255, 255));
        ShowPass1.setText("Show");
        ShowPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPass1ActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        ShowPass2.setForeground(new java.awt.Color(255, 255, 255));
        ShowPass2.setText("Show");
        ShowPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPass2ActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 450, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login_Frame.png"))); // NOI18N
        jLabel1.setText("Frame");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void Return_Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_Login_ButtonActionPerformed
        Login_Frame Login = new Login_Frame();
        Login.show();
        
        dispose();
    }//GEN-LAST:event_Return_Login_ButtonActionPerformed

    private void Password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password2ActionPerformed

    private void Password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password1ActionPerformed

    private void ShowPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowPass1ActionPerformed

    private void ShowPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowPass2ActionPerformed

    private void Create_Account_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_Account_ButtonActionPerformed
         if(Username.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out username");
            } 
         if(Email_Address.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out email");
            }
         else if(Password1.getText().equals("") || Password2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out both passwords");
            }
         else if(!Password1.getText().equals(Password2.getText())) {
            JOptionPane.showMessageDialog(null, "Passwords do not match");
            }
          
    }//GEN-LAST:event_Create_Account_ButtonActionPerformed

    private void Email_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_AddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create_Account_Button;
    private javax.swing.JTextField Email_Address;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JPasswordField Password2;
    private javax.swing.JButton Return_Login_Button;
    private javax.swing.JCheckBox ShowPass1;
    private javax.swing.JCheckBox ShowPass2;
    private javax.swing.JTextField Username;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
